<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <PathMap>$(MSBuildThisFileDirectory)=/src/</PathMap>
    <Version>0.4.16</Version>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>
  </PropertyGroup>
</Project>
