import fs from 'node:fs';
import crypto from 'node:crypto';
const root = new URL('../', import.meta.url);
const source = new URL('artifacts/windows/JjogaeStatus.exe', root);
const output = new URL('artifacts/release/', root);
const bytes = fs.readFileSync(source);
if (bytes.subarray(0, 2).toString() !== 'MZ') throw new Error('Not a Windows executable');
const pe = bytes.readUInt32LE(0x3c);
if (bytes.toString('ascii', pe, pe + 4) !== 'PE\0\0' || bytes.readUInt16LE(pe + 4) !== 0x8664) throw new Error('Expected x64 Windows PE');
fs.mkdirSync(output, { recursive: true });
fs.copyFileSync(source, new URL('JjogaeStatus.exe', output));
for (const file of ['README.md', 'PRIVACY.md']) fs.copyFileSync(new URL(file, root), new URL(file, output));
const checksum = crypto.createHash('sha256').update(bytes).digest('hex');
fs.writeFileSync(new URL('SHA256SUMS.txt', output), `${checksum}  JjogaeStatus.exe\n`);
const note = 'Windows 10/11 x64용 쪼개 상황실입니다. JjogaeStatus.exe를 실행하세요. 로그인 창이 열리지 않으면 Microsoft 공식 WebView2 Runtime을 설치해 주세요.\n';
fs.writeFileSync(new URL('먼저 읽어주세요.txt', output), note);
console.log(JSON.stringify({ name: 'JjogaeStatus.exe', bytes: bytes.length, sha256: checksum, platform: 'Windows x64' }));
